<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260509171031 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE conversations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_dernier_message TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user1_id INT NOT NULL, user2_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C2521BF156AE248B ON conversations (user1_id)');
        $this->addSql('CREATE INDEX IDX_C2521BF1441B8B65 ON conversations (user2_id)');
        $this->addSql('CREATE TABLE disponibilites (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jour_semaine INT NOT NULL, heure_debut TIME(0) WITHOUT TIME ZONE NOT NULL, heure_fin TIME(0) WITHOUT TIME ZONE NOT NULL, est_disponible BOOLEAN NOT NULL, mentor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B0F3489CDB403044 ON disponibilites (mentor_id)');
        $this->addSql('CREATE TABLE feedbacks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note INT NOT NULL, commentaire TEXT DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, mentorat_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7E6C3F8999A98569 ON feedbacks (mentorat_id)');
        $this->addSql('CREATE TABLE mentorats (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(20) NOT NULL, demande_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reponse_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, message TEXT DEFAULT NULL, eleve_id INT NOT NULL, mentor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_890A1105A6CC7B2 ON mentorats (eleve_id)');
        $this->addSql('CREATE INDEX IDX_890A1105DB403044 ON mentorats (mentor_id)');
        $this->addSql('CREATE TABLE messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, date_envoi TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, est_lu BOOLEAN NOT NULL, conversation_id INT NOT NULL, expediteur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB021E969AC0396 ON messages (conversation_id)');
        $this->addSql('CREATE INDEX IDX_DB021E9610335F61 ON messages (expediteur_id)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, titre VARCHAR(100) NOT NULL, message VARCHAR(255) NOT NULL, lien VARCHAR(255) DEFAULT NULL, est_lue BOOLEAN NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE TABLE parcours (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, est_complete BOOLEAN NOT NULL, user_id INT NOT NULL, filiere_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_99B1DEE3A76ED395 ON parcours (user_id)');
        $this->addSql('CREATE INDEX IDX_99B1DEE3180AA129 ON parcours (filiere_id)');
        $this->addSql('CREATE TABLE parcours_etapes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ordre INT NOT NULL, type VARCHAR(30) NOT NULL, reference_id INT NOT NULL, est_complete BOOLEAN NOT NULL, parcours_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EDE497CB6E38C0DB ON parcours_etapes (parcours_id)');
        $this->addSql('CREATE TABLE quiz_questions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, texte TEXT NOT NULL, ordre INT DEFAULT NULL, quiz_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8CBC2533853CD175 ON quiz_questions (quiz_id)');
        $this->addSql('CREATE TABLE quiz_reponses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, texte VARCHAR(255) NOT NULL, est_correcte BOOLEAN NOT NULL, points INT DEFAULT NULL, question_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C895D7831E27F6BF ON quiz_reponses (question_id)');
        $this->addSql('CREATE TABLE quizs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(30) NOT NULL, duree INT DEFAULT NULL, est_actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE recommandations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, reference_id INT NOT NULL, titre VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, score DOUBLE PRECISION NOT NULL, est_vue BOOLEAN NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2E7C1FDBA76ED395 ON recommandations (user_id)');
        $this->addSql('CREATE TABLE rendez_vous (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_heure TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duree INT DEFAULT NULL, lien_visio VARCHAR(255) DEFAULT NULL, statut VARCHAR(20) NOT NULL, mentorat_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65E8AA0A99A98569 ON rendez_vous (mentorat_id)');
        $this->addSql('CREATE TABLE user_quiz_results (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, score INT DEFAULT NULL, total_points INT DEFAULT NULL, date_completion TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resultat JSON DEFAULT NULL, user_id INT NOT NULL, quiz_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D3535B6A76ED395 ON user_quiz_results (user_id)');
        $this->addSql('CREATE INDEX IDX_D3535B6853CD175 ON user_quiz_results (quiz_id)');
        $this->addSql('ALTER TABLE conversations ADD CONSTRAINT FK_C2521BF156AE248B FOREIGN KEY (user1_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversations ADD CONSTRAINT FK_C2521BF1441B8B65 FOREIGN KEY (user2_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE disponibilites ADD CONSTRAINT FK_B0F3489CDB403044 FOREIGN KEY (mentor_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feedbacks ADD CONSTRAINT FK_7E6C3F8999A98569 FOREIGN KEY (mentorat_id) REFERENCES mentorats (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mentorats ADD CONSTRAINT FK_890A1105A6CC7B2 FOREIGN KEY (eleve_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mentorats ADD CONSTRAINT FK_890A1105DB403044 FOREIGN KEY (mentor_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E969AC0396 FOREIGN KEY (conversation_id) REFERENCES conversations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT FK_DB021E9610335F61 FOREIGN KEY (expediteur_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE parcours ADD CONSTRAINT FK_99B1DEE3A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE parcours ADD CONSTRAINT FK_99B1DEE3180AA129 FOREIGN KEY (filiere_id) REFERENCES filiere (id)');
        $this->addSql('ALTER TABLE parcours_etapes ADD CONSTRAINT FK_EDE497CB6E38C0DB FOREIGN KEY (parcours_id) REFERENCES parcours (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quiz_questions ADD CONSTRAINT FK_8CBC2533853CD175 FOREIGN KEY (quiz_id) REFERENCES quizs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE quiz_reponses ADD CONSTRAINT FK_C895D7831E27F6BF FOREIGN KEY (question_id) REFERENCES quiz_questions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE recommandations ADD CONSTRAINT FK_2E7C1FDBA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A99A98569 FOREIGN KEY (mentorat_id) REFERENCES mentorats (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_quiz_results ADD CONSTRAINT FK_D3535B6A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_quiz_results ADD CONSTRAINT FK_D3535B6853CD175 FOREIGN KEY (quiz_id) REFERENCES quizs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE app_user ADD specialite VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE app_user ADD biographie TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE app_user ADD experience INT DEFAULT NULL');
        $this->addSql('ALTER TABLE app_user ADD note_moyenne DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE app_user ADD nb_avis INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE conversations DROP CONSTRAINT FK_C2521BF156AE248B');
        $this->addSql('ALTER TABLE conversations DROP CONSTRAINT FK_C2521BF1441B8B65');
        $this->addSql('ALTER TABLE disponibilites DROP CONSTRAINT FK_B0F3489CDB403044');
        $this->addSql('ALTER TABLE feedbacks DROP CONSTRAINT FK_7E6C3F8999A98569');
        $this->addSql('ALTER TABLE mentorats DROP CONSTRAINT FK_890A1105A6CC7B2');
        $this->addSql('ALTER TABLE mentorats DROP CONSTRAINT FK_890A1105DB403044');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E969AC0396');
        $this->addSql('ALTER TABLE messages DROP CONSTRAINT FK_DB021E9610335F61');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE parcours DROP CONSTRAINT FK_99B1DEE3A76ED395');
        $this->addSql('ALTER TABLE parcours DROP CONSTRAINT FK_99B1DEE3180AA129');
        $this->addSql('ALTER TABLE parcours_etapes DROP CONSTRAINT FK_EDE497CB6E38C0DB');
        $this->addSql('ALTER TABLE quiz_questions DROP CONSTRAINT FK_8CBC2533853CD175');
        $this->addSql('ALTER TABLE quiz_reponses DROP CONSTRAINT FK_C895D7831E27F6BF');
        $this->addSql('ALTER TABLE recommandations DROP CONSTRAINT FK_2E7C1FDBA76ED395');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A99A98569');
        $this->addSql('ALTER TABLE user_quiz_results DROP CONSTRAINT FK_D3535B6A76ED395');
        $this->addSql('ALTER TABLE user_quiz_results DROP CONSTRAINT FK_D3535B6853CD175');
        $this->addSql('DROP TABLE conversations');
        $this->addSql('DROP TABLE disponibilites');
        $this->addSql('DROP TABLE feedbacks');
        $this->addSql('DROP TABLE mentorats');
        $this->addSql('DROP TABLE messages');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE parcours');
        $this->addSql('DROP TABLE parcours_etapes');
        $this->addSql('DROP TABLE quiz_questions');
        $this->addSql('DROP TABLE quiz_reponses');
        $this->addSql('DROP TABLE quizs');
        $this->addSql('DROP TABLE recommandations');
        $this->addSql('DROP TABLE rendez_vous');
        $this->addSql('DROP TABLE user_quiz_results');
        $this->addSql('ALTER TABLE app_user DROP specialite');
        $this->addSql('ALTER TABLE app_user DROP biographie');
        $this->addSql('ALTER TABLE app_user DROP experience');
        $this->addSql('ALTER TABLE app_user DROP note_moyenne');
        $this->addSql('ALTER TABLE app_user DROP nb_avis');
    }
}
