<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260509164228 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE forum_categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, ordre INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE forum_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, auteur_id INT NOT NULL, sujet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FCF1937160BB6FE6 ON forum_messages (auteur_id)');
        $this->addSql('CREATE INDEX IDX_FCF193717C4D497E ON forum_messages (sujet_id)');
        $this->addSql('CREATE TABLE forum_sujets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, contenu TEXT DEFAULT NULL, is_resolu BOOLEAN NOT NULL, is_epingle BOOLEAN NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_dernier_message TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, auteur_id INT NOT NULL, categorie_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D31007A60BB6FE6 ON forum_sujets (auteur_id)');
        $this->addSql('CREATE INDEX IDX_8D31007ABCF5E72D ON forum_sujets (categorie_id)');
        $this->addSql('ALTER TABLE forum_messages ADD CONSTRAINT FK_FCF1937160BB6FE6 FOREIGN KEY (auteur_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_messages ADD CONSTRAINT FK_FCF193717C4D497E FOREIGN KEY (sujet_id) REFERENCES forum_sujets (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_sujets ADD CONSTRAINT FK_8D31007A60BB6FE6 FOREIGN KEY (auteur_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE forum_sujets ADD CONSTRAINT FK_8D31007ABCF5E72D FOREIGN KEY (categorie_id) REFERENCES forum_categories (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE forum_messages DROP CONSTRAINT FK_FCF1937160BB6FE6');
        $this->addSql('ALTER TABLE forum_messages DROP CONSTRAINT FK_FCF193717C4D497E');
        $this->addSql('ALTER TABLE forum_sujets DROP CONSTRAINT FK_8D31007A60BB6FE6');
        $this->addSql('ALTER TABLE forum_sujets DROP CONSTRAINT FK_8D31007ABCF5E72D');
        $this->addSql('DROP TABLE forum_categories');
        $this->addSql('DROP TABLE forum_messages');
        $this->addSql('DROP TABLE forum_sujets');
    }
}
