
accueil_site: 
    path: /accueil              
    controller: App\Controller\MainController::index

liste_ecoles: 
    path: /liste_etablissement   
    controller: App\Controller\SchoolController::liste